### ISSUE TITLE
HTML, PDF und EPUB Versionen

### ISSUE THREAD

**Issue by probonopd** [pbouda/pyqt-und-pyside-buch#1]
Vielen Dank für die Veröffentlichung unter einer CC Lizenz.

Ist es inzwischen möglich HTML, PDF und EPUB Versionen zu generieren oder muss dazu noch etwas arbeitsintensives getan werden?

**Comment by pbouda** [comment]
Zustand unbekannt ehrlich gesagt :) Ich habe schon lange nicht mehr mit LaTex gearbeitet und kann im Moment da nichts ausprobieren. Hier ist aber die letzte Version die ich gebaut habe als PDF:

https://github.com/pbouda/pyqt-und-pyside-buch/releases/tag/1.0

**Comment by probonopd** [comment]
Dankeschön, sehr hilfreich. Vielen Dank für dieses nützliche Buch.
